//SALE METHOD
export const GET_SALES = "GET_SALES";
export const GET_SALES_FULFILLED = "GET_SALES_FULFILLED";
export const GET_SALES_REJECTED = "GET_SALES_REJECTED";

export const SALE_EDIT_REQUEST = "SALE_EDIT_REQUEST";
export const GET_SALE_DETAIL = "GET_SALE_DETAIL";
export const GET_SALE_DETAIL_FULFILLED = "GET_SALE_DETAIL_FULFILLED";
export const GET_SALE_DETAIL_REJECTED = "GET_SALE_DETAIL_REJECTED";

export const POST_SALE = "POST_SALE";
export const POST_SALE_SUCCESS = "POST_SALE_SUCCESS";
export const POST_SALE_ERROR = "POST_SALE_ERROR";

export const PRODUCT_LIST = "PRODUCT_LIST";
export const STORE_LIST = "STORE_LIST";
export const CUSTOMER_LIST = "CUSTOMER_LIST";

export const UPDATE_SALE = "UPDATE_SALE";
export const UPDATE_SALE_SUCCESS = "UPDATE_SALE_SUCCESS";
export const UPDATE_SALE_ERROR = "UPDATE_SALE_ERROR";

export const DELETE_SALE = "DELETE_SALE";
export const DELETE_SALE_SUCCESS = "DELETE_SALE_SUCCESS";
export const DELETE_SALE_ERROR = "DELETE_SALE_ERROR";
export const DELETE_SALE_CANCEL = "DELETE_SALE_CANCEL";

export const SALE_ORDERBY_NAME = "SALE_ORDERBY_NAME";
export const SALE_ORDERBY_CUSTOMER = "SALE_ORDERBY_CUSTOMER";
export const SALE_ORDERBY_PRODUCT = "SALE_ORDERBY_PRODUCT";
export const SALE_ORDERBY_STORE = "SALE_ORDERBY_STORE";
export const SALE_ORDERBY_DATE = "SALE_ORDERBY_DATE";