
//CUSTOMER METHOD
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMERS_FULFILLED = "GET_CUSTOMERS_FULFILLED";
export const GET_CUSTOMERS_REJECTED = "GET_CUSTOMERS_REJECTED";

export const CUSTOMER_EDIT_REQUEST = "CUSTOMER_EDIT_REQUEST";
export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
export const GET_CUSTOMER_DETAIL_FULFILLED = "GET_CUSTOMER_DETAIL_FULFILLED";
export const GET_CUSTOMER_DETAIL_REJECTED = "GET_CUSTOMER_DETAIL_REJECTED";

export const POST_CUSTOMER = "POST_CUSTOMER";
export const POST_CUSTOMER_SUCCESS = "POST_CUSTOMER_SUCCESS";
export const POST_CUSTOMER_ERROR = "POST_CUSTOMER_ERROR";

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_ERROR = "UPDATE_CUSTOMER_ERROR";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR";
export const DELETE_CUSTOMER_CANCEL = "DELETE_CUSTOMER_CANCEL";



//MODAL METHOD
export const OPEN_MODAL = "OPEN MODAL";
export const CLOSE_MODAL = "CLOSE MODAL";
export const ERROR_IN_MODAL = "CLOSE MODAL";

//Paging Changed
export const PAGING_SET = "PAGING_SET";
export const PAGE_CHANGED = "PAGE_CHANGED";
export const PAGESIZE_DATA_CHANGED = "PAGESIZE_DATA_CHANGED";

//OrderBy
export const CUSTOMER_ORDERBY_NAME = "CUSTOMER_ORDERBY_NAME";
export const CUSTOMER_ORDERBY_ADDRESS = "CUSTOMER_ORDERBY_ADDRESS";

