//STORE METHOD
export const GET_STORES = "GET_STORES";
export const GET_STORES_FULFILLED = "GET_STORES_FULFILLED";
export const GET_STORES_REJECTED = "GET_STORES_REJECTED";

export const STORE_EDIT_REQUEST = "STORE_EDIT_REQUEST";
export const GET_STORE_DETAIL = "GET_STORE_DETAIL";
export const GET_STORE_DETAIL_FULFILLED = "GET_STORE_DETAIL_FULFILLED";
export const GET_STORE_DETAIL_REJECTED = "GET_STORE_DETAIL_REJECTED";

export const POST_STORE = "POST_STORE";
export const POST_STORE_SUCCESS = "POST_STORE_SUCCESS";
export const POST_STORE_ERROR = "POST_STORE_ERROR";

export const UPDATE_STORE = "UPDATE_STORE";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_ERROR = "UPDATE_STORE_ERROR";

export const DELETE_STORE = "DELETE_STORE";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_ERROR = "DELETE_STORE_ERROR";
export const DELETE_STORE_CANCEL = "DELETE_STORE_CANCEL";


export const STORE_ORDERBY_NAME = "STORE_ORDERBY_NAME";
export const STORE_ORDERBY_ADDRESS = "STORE_ORDERBY_ADDRESS";
