export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FULFILLED = "GET_PRODUCTS_FULFILLED";
export const GET_PRODUCTS_REJECTED = "GET_PRODUCTS_REJECTED";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_FULFILLED = "GET_PRODUCT_DETAIL_FULFILLED";
export const GET_PRODUCT_DETAIL_REJECTED = "GET_PRODUCT_DETAIL_REJECTED";

export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
export const DELETE_PRODUCT_CANCEL = "DELETE_PRODUCT_CANCEL";

export const PRODUCT_ORDERBY_NAME = "PRODUCT_ORDERBY_NAME";
export const PRODUCT_ORDERBY_PRICE = "PRODUCT_ORDERBY_PRICE";
